name: Publish to cako publisher
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Setup Node.js and vsce
        uses: actions/setup-node
        with:
          node-version: 14
      - name: Install vsce
        run: npm install -g vsce
      - name: Build and package extension
        run: |
          npm install
          vsce package
      - name: Publish extension to Visual Studio Code marketplace
        env:
          VSCE_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        uses: vsciot-vscode.vscode-iot-workbench-publish-extension
        with:
          args: publish -p $VSCE_PERSONAL_ACCESS_TOKEN